### ISSUE TITLE
Unable to pull docker image

### ISSUE THREAD

**Issue by kalinwilson** [autom8ter/oauth-graphql-playground#1]
Docker pull results in:
$ docker pull colemanword:oauth-graphql-playground:v0.0.3
invalid reference format

I don't have Go installed, so I can't build from source.
Any chance of getting binaries for Windows and/or Linux?

**Comment by thorstenbaek** [comment]
try 
$ docker pull colemanword/oauth-graphql-playground:v0.0.3
